In [ ]:
simple_error_doc = []

In [ ]:
# matrix completion!!! Mapping the gene lines to new environments
import numpy as np
import csv

def swap_columns(matrix, col1, col2):
    for row in matrix:
        row[col1], row[col2] = row[col2], row[col1]

mat_name2 = 'RPunch1415_Original.csv'
with open(mat_name2) as f:
  reader2 = csv.reader(f)
  lst2 = list(reader2)
  original = np.array(lst2)
  #print(mat)

original = np.delete(original,0,0)
original = np.delete(original,0,1)
original = original.astype(float)
mat = original.copy()
mat[0:194,4] = 0
swap_columns(mat,4,4)
swap_columns(original,4,4)
#print(mat)
#print(original)

In [ ]:
hori_piece = mat[195:775,:]
verti_piece = mat[:,0:4]
key_piece = mat[195:775,0:4]

inv = np.linalg.pinv(key_piece)
#print(inv)

SimpleMap = verti_piece @ inv @ hori_piece
#print(hori_piece.shape)
#print(verti_piece.shape)
#print(key_piece.shape)

In [ ]:
sqEr = 0

for y in range(mat.shape[1]): # change according to size
  for x in range(mat.shape[0]): # change according to size
    if(mat[x,y]== 0):
      sqEr = sqEr + abs(1 - SimpleMap[x,y]/original[x,y])
      simple_error_doc.append(1 - SimpleMap[x,y]/original[x,y])

print(sqEr)

30.616713009400705


In [ ]:
print(len(simple_error_doc))

970


In [ ]:
from google.colab import files

file1_name = "Simple_1415_25_doc.txt"
simple_error_doc = [str(item) for item in simple_error_doc]

with open(file1_name, 'w') as file:
  for item in simple_error_doc:
        file.write(item + '\n')

files.download(file1_name)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
np.set_printoptions(threshold=np.inf)
print(SimpleMap)

[[ 5.07390009  5.07390009  4.31186282  5.07390009 13.02220189]
 [ 6.13134032  6.13134032  6.02924363  6.13134032 17.72437191]
 [ 5.50562246  5.50562246  5.98534499  5.50562246 17.3031294 ]
 [ 5.44821661  5.44821661  5.53210146  5.44821661 16.17361914]
 [ 5.10631631  5.10631631  6.30144583  5.10631631 17.86994998]
 [ 5.01274534  5.01274534  5.72852952  5.01274534 16.43164419]
 [ 5.42241311  5.42241311  6.21439273  5.42241311 17.81750097]
 [ 5.47699967  5.47699967  5.71513685  5.47699967 16.63257065]
 [ 5.45373288  5.45373288  5.58120828  5.45373288 16.2956426 ]
 [ 5.86280644  5.86280644  6.97406573  5.86280644 19.88372003]
 [ 5.58332269  5.58332269  6.46811309  5.58332269 18.51454127]
 [ 5.37765294  5.37765294  6.01498846  5.37765294 17.3107657 ]
 [ 5.48318089  5.48318089  6.10204185  5.48318089 17.57522812]
 [ 5.95094341  5.95094341  6.50171372  5.95094341 18.78099303]
 [ 5.51583935  5.51583935  6.46974286  5.51583935 18.48456516]
 [ 5.31528813  5.31528813  6.03819531  5.31528813 17.33

In [ ]:
# Simple Method for completing blocked matrix
dim = mat.shape
count_hori = 0
count_verti = 0

for i in range(dim[1]): # change according to horizontal size
  if(mat[0,i] != 0):
    print(i)
    count_hori = i
print(mat[0,3])

for j in range(dim[0]): # change according to vertical size
  if(mat[j,dim[1]-1] != 0):
    count_verti = count_verti + 1
print(count_verti)

hori_piece = np.zeros([count_verti,dim[1]])  # change numbers of columns
verti_piece = np.zeros([dim[0],count_hori]) # change numbers of rows
key_piece = np.zeros([count_verti, count_hori])
#print(hori_piece)
#print(verti_piece)
#print(key_piece)

for i in range(dim[0] - count_verti,dim[0]):
  for j in range(dim[1]):
    hori_piece[i - dim[0] + count_verti,j] = mat[i,j]

for i in range(dim[0]):
  for j in range(0, count_hori):
    verti_piece[i,j] = mat[i,j]

for i in range(dim[0] - count_verti,dim[0]):
  for j in range(count_hori):
    key_piece[i - dim[0] + count_verti,j] = mat[i,j]

#print(hori_piece)
#print(verti_piece)
#print(key_piece)

inv = np.linalg.pinv(key_piece)
#print(inv)

SimpleMap = verti_piece @ inv @ hori_piece
#print(hori_piece.shape)

0
1
2
0.0
383
